### ISSUE TITLE
Timeout when installing with yarn

### ISSUE THREAD

**Issue by krislefeber** [jacobwgillespie/styled-icons#1045]
When attempting to install with yarn, I kept getting error messages about timeouts. After googling around for similar issues, I saw [this comment](https://github.com/yarnpkg/yarn/issues/6221#issuecomment-412844630) stating that the timeout can be increased with `--timeout 500000`, making the issue go away. Just thought I should mention this for others that see the problem. It's not necessarily that my internet connection was slow, but it seems that yarn includes the time to unpack the .tgz file in the timeout.

**Comment by jacobwgillespie** [comment]
Thanks for the report - are you by chance using Windows?  We have seen this issue with yarn before, but always on Windows so far (#785, #420).

But yes it does seem to be an issue with Yarn timeouts.

**Comment by krislefeber** [comment]
Yes, this was on Windows, but I was using Windows subsystem for Linux (WSL). I'm not sure if that makes a difference, as I believe I was technically running on an Ubuntu VM. I'll close out my issue.
