### ISSUE TITLE
Export individual packages

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#1055]
**Problem**

Because `styled-icons` includes different packages with multiple assets in them, it's currently pretty heavy (currently more than 100MB).

**Proposed solution**

One way to improve that would be to export individual packages. Eg. `@styled-icons/icomoon`, `@styled-icons/font-awesome`...etc

So users would import only the libraries that they need. Another benefit if the release system is clever enough to only push updated libraries is that you wouldn't get updates for libraries that you don't use.

**Comment by jacobwgillespie** [comment]
Yep, nice idea and I understand the context from the referenced issue - let me see if I can wire this up 👍

**Comment by stramel** [comment]
👍🏼 I had actually been thinking about this as well
