### ISSUE TITLE
Site is down

### ISSUE THREAD

**Issue by raulfdm** [jacobwgillespie/styled-icons#1061]
Just want to say the website is down.

<img width="1792" alt="Screenshot 2019-11-23 at 13 51 46" src="https://user-images.githubusercontent.com/12464600/69478947-6a053c80-0df8-11ea-91a3-a623867b1949.png">

I'm not sure if it's a region problem.

**Comment by janosh** [comment]
Might be due to [disabling netlify deploys](https://github.com/jacobwgillespie/styled-icons/commit/f0af930951c9ff4efb09f2f7f01bf625d13f2ffd) and [CircleCI deploys](https://github.com/jacobwgillespie/styled-icons/commit/71232bcb383fc5c8b8cb3072e6da587a08705164) not working as expected.

**Comment by LHudson73** [comment]
heh

**Comment by raulfdm** [comment]
Well... apparently is working again. :)

**Comment by jacobwgillespie** [comment]
Thanks for catching this, the site hosting was moved to Zeit Now and it temporary got into a redirect loop while [changing DNS](https://github.com/js-org/js.org/pull/3550) - should be all set now
