### ISSUE TITLE
Invalid assignment [./~/@styled-icons/styled-icon/dist/index.esm.js:9,0]

### ISSUE THREAD

**Issue by jakub-astrahit** [jacobwgillespie/styled-icons#1119]
After upgrading styled-icons from 8.6.0 to 9.1.0, I get this error when I build my app for production:

```
ERROR in module.js from UglifyJs
Invalid assignment [./~/@styled-icons/styled-icon/dist/index.esm.js:9,0][module.js:59917,44]
```

This is my definition of UglifyJs:
```
 new webpack.optimize.UglifyJsPlugin({
          // https://github.com/angular/angular/issues/10618
          mangle: {
            keep_fnames: true,
          },
          sourceMap: true,
          compress: {
            warnings: false,
          },
          parallel: true,
          comments: false,
        }),
```

Any ideas what the "Invalid assignment" means?

**Comment by jacobwgillespie** [comment]
I believe this relates to the fact that UglifyJs built into Webpack is very old and cannot handle some modern ES syntax.  I would recommend switching to `terser-webpack-plugin` (https://github.com/webpack-contrib/terser-webpack-plugin) which is more modern and is the recommended replacement for Uglify.  You might also be able to fix this with the external UglifyJS plugin: https://webpack.js.org/plugins/uglifyjs-webpack-plugin/
