### ISSUE TITLE
Slow dev time

### ISSUE THREAD

**Issue by simjoeweb** [jacobwgillespie/styled-icons#1123]
I've just added this module to my next.js app and my development environment is at least 7x slower: hot reloading and auto completion in visual code... I went from almost instant changes (<1s) to 7-8 seconds. But build time hasn't been much affected.

It has something to do with this library because I rolled back my app just before and after having this module to make sure. Has anyone had this issue?

**Comment by stramel** [comment]
@simjoeweb We're aware that Next.js app is taking a while to build and seems to be a common issue when you get to a large project https://github.com/zeit/next.js/issues/7929

**Comment by jacobwgillespie** [comment]
@simjoeweb how are you importing icons?  Are you importing whole packs like `import {material} from 'styled-icons'` or individual items like `import {Alert} from 'styled-icons/material'`?

**Comment by simjoeweb** [comment]
I am importing like this `import {Alert} from 'styled-icons/material'`
I went back to my old way of importing icons. The dev performance ruins it for me (I have to wait 20s+ to hot reload on some pages). I'll investigate further when I have the time because I like the convenience of this module.

**Comment by simjoeweb** [comment]
I solved it by importing packages I needed individually.
I think it could be worth mentioning this feature in the readme
