### ISSUE TITLE
Donation flow

### ISSUE THREAD

**Issue by tavurth** [jacobwgillespie/styled-icons#1142]
Awesome project, thank you for making icons so easy!

Could we add something like a PayPal link for donation to the Readme.md?

**Comment by jacobwgillespie** [comment]
Hey, thanks, I'm glad you're enjoying it! ❤️ 

This is the first request for a donation link I've gotten, but If you'd like to donate, there's three ways I think:

* GitHub sponsors: https://github.com/sponsors/jacobwgillespie
* My personal PayPal: https://paypal.me/jacobwgillespie
* OpenCollective: https://opencollective.com/styled-icons

**Comment by tavurth** [comment]
Thank you! 

I just saw that you also have it at the end of the Readme as well, but I didn't think to search for contributors!
