### ISSUE TITLE
How to make icon spin

### ISSUE THREAD

**Issue by cristiancs** [jacobwgillespie/styled-icons#1148]
With react-fontawesome you can pass the attribute spin and it will make the icon spin, it's is possible to do it with this library?

**Comment by stramel** [comment]
@cristiancs Yes, you can make icons spin with a bit of CSS.

Here I'm using `styled-components` to accomplish it but any method is fine.

```js
import styled, { keyframes } from 'styled-components'
import { Close } from 'styled-icons/material'

const spin = keyframes`
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
`

const SpinningIcon = styled(Close)`
  animation: 2s linear ${spin} infinite;
`
```
