### ISSUE TITLE
extend generic version of styled components

### ISSUE THREAD

**Issue by polaroidkidd** [jacobwgillespie/styled-icons#1151]
What I'm looking to do is something like this:

```typescript jsx


import { Generic } from 'styled-icons/root-style';
import { Blog } from 'styled-icons/fa-solid/Blog';

const IconWithRedBackground = styled(Generic)`
  background-color: 'red';
`;

const Example: React.FC = () => (<Blog/>)

```

... and then the `<Blog/>` renders with a red background. Is this at all possible or would I have to apply the style to every Icon I use specifically?

**Comment by stramel** [comment]
@polaroidkidd Are you wanting to globally modify `styled-icons` to where all icons have a red background?

**Comment by polaroidkidd** [comment]
@stramel for starters, yes.

**Comment by jacobwgillespie** [comment]
Hey @polaroidkidd, yes this is possible! What you will want to do is create a styled component wrapper that contains your app, and inside the CSS there, you would target `StyledIconBase` component from `@styled-icons/styled-icon` as a child of the wrapper, like so:

```typescript
import React from 'react'
import styled from 'styled-components'
import {StyledIconBase} from '@styled-icons/styled-icon'

const IconStyleWrapper = styled.div`
  ${StyledIconBase} {
    color: red;
    /* other styles for all icons here */
  }
`

export function App() {
  return (
    <IconStyleWrapper>
      {...}
    </IconStyleWrapper>
  )
}
```

Then all icons you use anywhere will be affected by that global style.

Here's a [**CodeSandbox example**](https://codesandbox.io/s/staging-snow-gwrlr).
