### ISSUE TITLE
Icons are not working in ie11 

### ISSUE THREAD

**Issue by addamove** [jacobwgillespie/styled-icons#1161]
Starting from 9.3 version

**Comment by jacobwgillespie** [comment]
Hey, is it https://styled-icons.js.org that's broken or your application?  The website won't work on IE11, but there shouldn't be anything as far as I know that would break `styled-icons` in IE11.

**Comment by addamove** [comment]
Yeah. My website doesn't work in ie11, it say some chunk doesn't have some method and this chunk was styled icon library. I doesn't remember error quite well. I just rolled back for one major version and everything started to work normally.

**Comment by jacobwgillespie** [comment]
Cool - I'll close this issue for now, but if you run into this again, feel free to post back here.  Even better, if you ever have a small example repo that's broken on IE11, I'd be happy to debug.
