### ISSUE TITLE
Drop individual icon imports from styled-icons package

### ISSUE THREAD

**Issue by jacobwgillespie** [jacobwgillespie/styled-icons#1171]
### Problem

So I can't publish `styled-icons` v9.6.0 because we have hit a file count limit and NPM is rejecting the publish. 🙂 There are now 67,776 files in that package after the addition of the `material-*` variant icon packs.

Today we are proxying all icons in the `styled-icons` package to the corresponding `@styled-icons/*` packages - we proxy both the pack as a whole and each individual icon.  Each proxied icon results in 5 files in the npm package.

### Proposal

We should release a new major release (v10) where only the icon packs themselves are proxied, and if consumers wish to import icons individually, they would need to import from `@styled-icons/pack`.  Specifically:

**Today (v9)**

```typescript
// Works:
import {material} from 'styled-icons'
import * as material from 'styled-icons/material'
import {Alarm} from 'styled-icons/material'
import {Alarm} from 'styled-icons/material/Alarm'

// Also works:
import * as material from '@styled-icons/material'
import {Alarm} from '@styled-icons/material'
import {Alarm} from '@styled-icons/material/Alarm'
```

**Proposed (v10)**

```typescript
// Works:
import {material} from 'styled-icons'
import * as material from 'styled-icons/material'
import {Alarm} from 'styled-icons/material'

// Does not work anymore:
import {Alarm} from 'styled-icons/material/Alarm'

// Still works:
import * as material from '@styled-icons/material'
import {Alarm} from '@styled-icons/material'
import {Alarm} from '@styled-icons/material/Alarm'
```

This would cut down the number of files to a very reasonable amount.

@stramel does this seem okay to you?

**Comment by stramel** [comment]
I was actually going to take a stab at re-working the structure last night but didn't get time to. 

I'm definitely on board for the proposed. Which is basically `styled-icons` becoming a bunch of `export * as material from '@styled-icons/material`.

With that being said, I'm not sure I see the benefit of maintaining that package anymore. If you want multiple, you could easily just pull in the packs you want. It will save install time. I imagine the primary use-case is a single package anyways.

We could add a deprecation notice for v10 and make `styled-icons` just a bunch of re-exports. ex.

```js
export * as foundation from '@styled-icons/foundation'
export * as material from '@styled-icons/material'
// ....
```

**Comment by jacobwgillespie** [comment]
Opened #1174 to implement this - I don't think want to necessarily deprecate `styled-icons` directly (as in, we don't want a NPM deprecation message) as I know some of the apps I work will will still want to import from `styled-icons` to pick up everything, but I've adjusted the docs to highlight the `@styled-icons/PACK` packages instead.

**Comment by stramel** [comment]
I was thinking by deprecation notice, it would be a console message maybe  a postinstall script that would encourage users to switch to the new syntax so in a future release we can drop support for styled-icons. But will leave it up to you

**Comment by jacobwgillespie** [comment]
> I was thinking by deprecation notice, it would be a console message maybe a postinstall script

If/when we do deprecate `styled-icons`, just a note that Yarn silences the output of all postinstall scripts, so only marking packages as deprecated on `npmjs.com` actually displays something in the consumer's terminal (NPM does display postinstall output IIRC).
