### ISSUE TITLE
v9.6.0 not published to npm

### ISSUE THREAD

**Issue by martinjuhasz** [jacobwgillespie/styled-icons#1182]
Hey, 
seems like you added some new icon sets in v9.6.0. F.e. i can find material-twotone on the websites' search. These are somehow not useable from the latest version that is on NPM => v0.9.5.

Would love to see the latest version published on NPM. Thanks for the effort!

**Comment by martinjuhasz** [comment]
If i would just read older issues =/
Duplicate of https://github.com/jacobwgillespie/styled-icons/issues/1171

**Comment by jacobwgillespie** [comment]
Yep, v9.6.0 couldn't publish because it was too large! 😱 v10.0.0 was just released, so this should be fixed now.

**Comment by martinjuhasz** [comment]
ty :)
