### ISSUE TITLE
Add IonIcons

### ISSUE THREAD

**Issue by Jensderond** [jacobwgillespie/styled-icons#1186]
- Name: `ionicons`
- License: `MIT`
- NPM package: `https://www.npmjs.com/package/ionicons`
- Website (if any): `https://ionicons.com`

**Comment by Jensderond** [comment]
I will implement this, **but...** is this more or less the same (but more up-to-date) icon pack as [open-iconic](https://github.com/iconic/open-iconic) or are the names just a bit similar?

Nevertheless I'll pick up adding **ionicons** 🎉

**Comment by jacobwgillespie** [comment]
Yeah, I think this is a separate icon pack, just similar names - feel free to submit a PR! ❤️
