### ISSUE TITLE
Can you add badges to styled icons?

### ISSUE THREAD

**Issue by onurcanavci** [jacobwgillespie/styled-icons#1197]
I would like to add a badge counter on icon but I don't find a documentation about this. Is there any way to add a badge to icons?

**Comment by stramel** [comment]
@onurcanavci What do you mean by "badge"? Do you have an example of what you're wanting to achieve?

**Comment by onurcanavci** [comment]
<img width="256" alt="Screen Shot 2020-03-14 at 12 36 10" src="https://user-images.githubusercontent.com/34331026/76679288-650b0980-65f0-11ea-91c3-35570c8d73dc.png">

Like this

**Comment by jacobwgillespie** [comment]
@onurcanavci yes you can, but not directly through this library - Styled Icons provides the icon SVG directly, so you would use it inside another component that paired the icon with a badge. Something like this:

```typescript
import React from 'react'

export const IconWithBadge = ({icon: Icon, badgeContents, iconProps = {}}) => (
  <div className={className}>
    <Badge>{badgeContents}</Badge>
    <Icon {...iconProps} />
  <div>
)
```

Then to use it:

```typescript
import React from 'react'
import {Alert} from '@styled-icons/material'
import {IconWithBadge} from './IconWithBadge'

export const Example = () => (
  <IconWithBadge
    icon={Alert}
    badgeContents="12"
  />
)
```

Note that the above is just an example, you would need to add CSS styles for the IconWithBadge wrapper and Badge component to display the badge correctly.

**Comment by stramel** [comment]
I think we can close this as this is just an implementation using an icon. Please feel free to comment if we're misunderstanding what you're looking for.
