### ISSUE TITLE
Missing Ionicons outline pack

### ISSUE THREAD

**Issue by germanf** [jacobwgillespie/styled-icons#1220]
Guys, the package `@styled-icons/ionicons-outline` isn't available on npm registry. 
Could you add it? Thanks!

**Comment by jacobwgillespie** [comment]
Hey, yes this is expected, we've encountered an issue where the SVG optimizer breaks the Ionicons icons - this is waiting on #1190 to be completed, after that it'll be published.

**Comment by akougblenou** [comment]
Does this concern the other packages from ionicons? I am unable to find anylooking a the npm registry.

**Comment by janosh** [comment]
Same here. Unable to import any of the ionicons.

Anything blocking #1190 that I might be able to help with?

**Comment by el1f** [comment]
Seems like it's affecting all the ionicons indeed. Been trying to add the sharp package with little success

**Comment by jacobwgillespie** [comment]
Okay, I have some free cycles today, let me see if I can fix the color issue (ionicons-outline failed to publish as the icon colors got mangled by an SVG optimizer).

**Comment by stramel** [comment]
@jacobwgillespie I can review quickly if you get around to it. If not, I was going to try to take a look today or tomorrow.

**Comment by jacobwgillespie** [comment]
@stramel Yep, exactly that (see https://github.com/svg-icons/svg-icons/pull/8) - I've switched back to the `svgo`-based optimizer, removing the Rust fork of `svgcleaner`, as while Rust is super cool, the JS is much more maintainable given the (lack of) available time I have at the moment. 🙂 

There's now a `CURRENT_COLOR` environment variable that can strip out colors conditionally - ionicons hard-codes the icon colors to `#000`, so for those packs specifically, we set the env var.

**Comment by jacobwgillespie** [comment]
This has been published as v10.3.0 - thank you all for your patience! 🎉 Let me know if you run into any issues.

**Comment by janosh** [comment]
@jacobwgillespie Can confirm ionicons working again in v10.3.0. Thanks a lot!

**Comment by el1f** [comment]
Wow, this was quick. Great job @jacobwgillespie!
