### ISSUE TITLE
Is possible to pass a styled icon as a prop to a wrapper component?

### ISSUE THREAD

**Issue by cmacdonnacha** [jacobwgillespie/styled-icons#1223]
I have a wrapper component called `IconButton` which will display a styled icon and also handle things like "hover" styles and click events. I'm not sure if I'm going down the correct path with this as I'm running into some typescript errors and was wondering if you could see what I was doing wrong.

Inside my `Header` component I would like to use my `IconButton` component, like so:

```
import React from 'react';
import styled from 'styled-components/macro';
import { MenuOutline } from '@styled-icons/evaicons-outline/MenuOutline';
import IconButton from './IconButton';

const Container = styled.header`
 ...
`;

const Header: React.FunctionComponent = () => {
  return (
    <Container>
      <IconButton icon={<MenuOutline size={40} />} />
    </Container>
  );
};
```

Then, inside the `IconButton` component I am using a `StyledIcon`:

```
import React from 'react';
import styled from 'styled-components/macro';
import { StyledIcon } from '@styled-icons/styled-icon';

interface Props {
  icon: StyledIcon;
  onClick?: () => void;
}

const Container = styled.div`
  &:hover {
    background-color: grey;
  }
`;

const IconButton: React.FunctionComponent<Props> = (props: Props) => {
  return <Container>{props.icon}</Container>;
};
```

When doing this I am seeing the following error:

```
TypeScript error in C:/dev/react-boilerplate/src/components/Header.tsx(24,8):
Property '$$typeOf' is missing in type '{ icon: Element; }' but required in type 'Props'.  TS2741
```

![image](https://user-images.githubusercontent.com/9777763/78140938-ad189180-7422-11ea-91a4-dc72e1fffd2b.png)

If I replace `StyledIcon` type with `any` it works fine. 

```
interface Props {
  icon: any; // works fine when changing this to 'any'
  onClick?: () => void;
}
```

Any ideas? Greatly appreciated!

**Comment by jacobwgillespie** [comment]
Hey, yep you can do this one of two ways, either passing the icon without props to another component, or changing your wrapper component type to accept any rendered React child:

```typescript
// This should work, leaving the icon prop as StyledIcon, note that the MenuOutline
// component is not rendered, it's passed as a value
<IconButton icon={MenuOutline} />
```

Or:

```
interface Props {
  icon: React.ReactNode;
  onClick?: () => void;
}
```

Basically `StyledIcon` refers to an unrendered icon component, and passing in `<MenuOutline size={40} />` is a rendered component.

**Comment by cmacdonnacha** [comment]
Thanks for the prompt reply! I actually do prefer your first suggestion and it's what I tried initially but I then ran into this React error:

```
Error: Objects are not valid as a React child (found: object with keys {$$typeof, render, displayName}). If you meant to render a collection of children, use an array instead.
    in div (created by IconButton__Button)
    in IconButton__Button (at IconButton.tsx:17)
```

**Comment by stramel** [comment]
You can use `React.ReactElement` instead to pass `<MenuOutline />` or to pass the icon component you can do `React.ComponentType<StyledIcon>` and pass `MenuOutline`

**Comment by cmacdonnacha** [comment]
Thanks @stramel 

I could be doing something wrong but I tried your second suggestion and I'm now getting:

`Type 'StyledIcon' is not assignable to type 'ComponentType<StyledIcon>'.`

When using it like this:

**Header.tsx**

```
import { MenuOutline } from '@styled-icons/evaicons-outline/MenuOutline';

<IconButton icon={MenuOutline} ariaLabel={'Open Sidebar'} onClick={props.onMenuButtonClicked} />
```

**IconButton.tsx**

```
import { StyledIcon } from '@styled-icons/styled-icon';

interface Props {
  icon: React.ComponentType<StyledIcon>;
  onClick?: () => void;
}
```

**Comment by cmacdonnacha** [comment]
Thanks @stramel 

I could be doing something wrong but I tried your second suggestion and I'm now getting:

`Type 'StyledIcon' is not assignable to type 'ComponentType<StyledIcon>'.`

When using it like this:

**Header.tsx**

```
import { MenuOutline } from '@styled-icons/evaicons-outline/MenuOutline';

<IconButton icon={MenuOutline} />
```

**IconButton.tsx**

```
import { StyledIcon } from '@styled-icons/styled-icon';

interface Props {
  icon: React.ComponentType<StyledIcon>;
  onClick?: () => void;
}
```

**Comment by stramel** [comment]
@cmacdonnacha Sorry for the incorrect information on the typing. I was trying to do it off the top of my head. You should be able to use `StyledIcon` directly or `React.ComponentType<StyledIconProps>`

**Comment by cmacdonnacha** [comment]
Thanks @stramel . Just tried that out and now I'm getting this error:

```
Error: Objects are not valid as a React child (found: object with keys {$$typeof, render, displayName}). If you meant to render a collection of children, use an array instead.
    in div (created by IconButton__Button)
    in IconButton__Button (at IconButton.tsx:17)
```

**Comment by stramel** [comment]
@cmacdonnacha Can you show your code for the IconButton?

**Comment by cmacdonnacha** [comment]
Yep you can see it at the top in my original post 👍🏻

**Comment by stramel** [comment]
The problem is your usage of the prop, not the typing.

Two Options: 

- `StyledIcon` / `ComponentType<StyledIconProps>` passed in as `MenuOutline` using `<props.icon />` to display (https://codesandbox.io/s/modest-rain-lwjyd)
- `ReactElement` / `ReactNode` passed in as `<MenuOutline />` using `{props.icon}` to display (https://codesandbox.io/s/wizardly-microservice-6tiiy)

**Comment by cmacdonnacha** [comment]
Ah! Excellent thanks for all your help!
