### ISSUE TITLE
Icon alignment

### ISSUE THREAD

**Issue by harry-sm** [jacobwgillespie/styled-icons#169]
Hello, Greate project.

I'm replacing my font-awesome icons with styled-icons, however, I have encountered an issue. The icon alignment is off.
![image](https://user-images.githubusercontent.com/15040197/41939708-a36a884c-7964-11e8-9c70-6d54189ee598.png)

My markup
![image](https://user-images.githubusercontent.com/15040197/41939764-b9cf2692-7964-11e8-9186-f75552b46286.png)

Using font-awesome
![image](https://user-images.githubusercontent.com/15040197/41939936-31b429f0-7965-11e8-9f3a-efa3a7785ee6.png)
![image](https://user-images.githubusercontent.com/15040197/41939963-3fb28f74-7965-11e8-8d6e-9fb0d4450584.png)

I see on the SVG element the class has the property `vertical-align: middle`. If I replace it `vertical-align: -.150em` similar to what font-awsome has the icons align properly.

**Comment by harry-sm** [comment]
This package
https://www.npmjs.com/package/@fortawesome/react-fontawesome
https://github.com/FortAwesome/react-fontawesome

Thanks for looking into it.

**Comment by jacobwgillespie** [comment]
Nice catch, it looks like Font Awesome applies a `vertical-align: -.125em` to all icons.  I added that to all Font Awesome icons in #171 and just released it to npm as `v2.3.0`.

**Comment by harry-sm** [comment]
Great! Thanks.

Just to point out the same issue occurs with octicons and material icons.

Oticon
![image](https://user-images.githubusercontent.com/15040197/41989998-2ba76cb6-7a0f-11e8-81c8-aa0b2be12904.png)

Material
![image](https://user-images.githubusercontent.com/15040197/41990048-54da27ea-7a0f-11e8-89db-01ebb39edf28.png)
`vertical-align: -.25em;` seems to fix the issue, but I haven't tested on all icons but I haven't tested on all icons or different sizes. I do wonder if there is a way to normalize the styles for the different icons.

**Comment by jacobwgillespie** [comment]
Hmm, interesting...  Yeah I think the other icon packs just set `vertical-align` to `middle`.  Even the Octicons website seems to have this same issue:

<img width="329" alt="screenshot 2018-06-28 10 56 38" src="https://user-images.githubusercontent.com/130874/42045805-10e4431e-7ac2-11e8-93b7-c3bb304e9ca2.png">

I had briefly looked at any automated ways to calculate the visual center of icons, so that might be interesting, since then it might be possible to calculate an automated `vertical-alignment` for all icons.  Not sure if it's doable or not though.

**Comment by harry-sm** [comment]
Yeah that's a lot of work. I see font-awesome using height: 1em. However,
as the size of the icon increase the misalignment becomes more pronounced.

On Jun 28, 2018 10:59 AM, "Jacob Gillespie" <notifications@github.com>
wrote:

Hmm, interesting... Yeah I think the other icon packs just set
vertical-align to middle. Even the Octicons website seems to have this same
issue:

[image: screenshot 2018-06-28 10 56 38]
<https://user-images.githubusercontent.com/130874/42045805-10e4431e-7ac2-11e8-93b7-c3bb304e9ca2.png>

I had briefly looked at any automated ways to calculate the visual center
of icons, so that might be interesting, since then it might be possible to
calculate an automated vertical-alignment for all icons. Not sure if it's
doable or not though.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jacobwgillespie/styled-icons/issues/169#issuecomment-401085384>,
or mute the thread

**Comment by harry-sm** [comment]
@jacobwgillespie 
I did an edit but, unfortunately, I am unable to run a build,  not all packages were installed so getting tons of errors about missing packages. I have no idea why. I just added some css to icon.tsx.template.
```css
height: ${({size}) => size ? (1 * size) + 'em' : '1em'};
vertical-align: ${({size}) => size ? (-.125 * size) + 'em' : '-.125em'};
```
The prop size would be represented in em units so
```tsx
<icon size={1} /> // would be 1em
<icon size={1.5} /> // would be 1.5em
```
Might be better to change the unit to rem, just a thought.
