### ISSUE TITLE
Tree Shaking isn't working as (I) expected

### ISSUE THREAD

**Issue by brad-decker** [jacobwgillespie/styled-icons#282]
Prior to stating the issue I want to say that the reason I have installed this package is I am trying to replace our custom icons from https://www.github.com/MerlinLabs/styled-material-components with yours. Also I am currently rewriting the library build process to get tree shaking working. I have been down a rabbit hole and even created a whole new package to test how Tree shaking works in general.

What i've noticed so far...as soon as you introduce styled-components into a file tree shaking fails entirely for that file. I was using your code to forensic analyze my process and realized that tree shaking doesn't work with styled-icons with current version of styled-components (3.4.5, not 4) and create react app. 

![image](https://user-images.githubusercontent.com/4448075/45269044-5fa58f80-b44c-11e8-98ba-4912cbb1794b.png)

```js
import React, { Component } from 'react';
import { NewPkgTest } from 'new-pkg';
import { AccountCircle } from 'styled-icons/material';
import logo from './logo.svg';
import './App.css';

class App extends Component {
  render() {
    return (
      <div className="App">
      <AccountCircle />
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.js</code> and save to reload.
        </p>
        <NewPkgTest />
      </div>
    );
  }
}

export default App;
```

The only file I have modified from the default create react app stack is the App.js file. I imported a single Icon from the material sub import and it includes all of the material icons in the generated bundle.

In dev mode it looks like the tree shaking is actually working so far as adding the comment to mark unused modules:
```js
/***/ "./node_modules/styled-icons/material/Add.js":
/*!***************************************************!*\
  !*** ./node_modules/styled-icons/material/Add.js ***!
  \***************************************************/
/*! exports provided: Add, AddDimensions */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
/* unused harmony export Add */
/* unused harmony export AddDimensions */
```

Can you provide me any help figuring this out? Would love to include styled-icons in our library and get our library figured out so tree shaking doesn't result in a huge bundle.

**Comment by jacobwgillespie** [comment]
Hey @brad-decker sorry for the late reply - do you have a sample repo or more information about your build environment?  If you are using Webpack 4 tree shaking should work out of the box, and other environments have their own requirements.  I'd be happy to take a look and we should be able to get everything working.

As a side note, the `unused harmony export` does indicate an export is unused, but won't be sufficient for Uglify to perform the tree shaking - for that, the builder would emit a `/*#__PURE__*/` comment, which authorizes Uglify to remove the unused code.

**Comment by jacobwgillespie** [comment]
I'm going to close this - if you're using Create React App things will be smoother with CRA v2, and if you're using Gatsby, things will also be smoother with v2.  If just plain Webpack, you should be on Webpack 4 and should not be transpiling ES modules before they arrive at Webpack (i.e. babel should be emitting modules).  Otherwise if that's not an option, the `.cjs` imports should work, they're just less ergonomic.

Feel free to post back with more details if you'd like though and I'd be happy to check them out!

**Comment by jacobwgillespie** [comment]
Yep, if you transpile to CommonJS before Webpack or Rollup or your bundler are able to parse the code, it won't be able to apply the ES modules tree shaking.  Webpack 4 (and therefore Create React App v2+ and Gatsby v2+) and Rollup are able to handle this out of the box.
