### ISSUE TITLE
Add search variable to URL params

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#387]
It would be nice to store search in URL params to be able to share URLs such as `https://styled-icons.js.org/?search=event` that would show the page with filtered icons.

**Comment by jacobwgillespie** [comment]
Awesome suggestion, I've added this!

https://styled-icons.js.org/?s=smile

Depending on what's cached locally, you might need to refresh after visiting the site to pick up the new changes in the service worker.

**Comment by Betree** [comment]
Nice one @jacobwgillespie and thanks for this library, it is really useful!

https://styled-icons.js.org/?s=thumbs%20up
