### ISSUE TITLE
Deprecation warning since upgrading to styled-components 4.1.0

### ISSUE THREAD

**Issue by bopfer** [jacobwgillespie/styled-icons#401]
See the notes about the deprecation here: https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v410---2018-11-12

Nothing breaks and everything will continue to work until styled-components v5.  But, the many warnings are an eyesore.

Any plans on updating styled-icons to the new functionality?

Edit: here is the full deprecation warning:
```
Functions as object-form attrs({}) keys are now deprecated and will be removed in a future version of styled-components. Switch to the new attrs(props => ({})) syntax instead for easier and more powerful composition. The attrs key in question is "children" on component "AlertTriangle"
```

**Comment by jacobwgillespie** [comment]
Thanks for reporting, this has been fixed in v4.0.0 🎉
