### ISSUE TITLE
5.2.1 Material icons index.js is empty

### ISSUE THREAD

**Issue by t3kkitz** [jacobwgillespie/styled-icons#439]
5.2.1 Material icons index.js is empty, so material icons is not exist. 5.2.0 is OK

**Comment by kadavrrr** [comment]
for me, only 5.1.0 works fine

**Comment by t3kkitz** [comment]
> for me, only 5.1.0 works fine

Yeah, I just rush with issue and don't check for other errors. And fallback later to v4.3

**Comment by jacobwgillespie** [comment]
Hey so sorry about that, looks like the build since v5.1.0 hasn't been properly reading those icons.  I just pushed out a fix for v5.2.2 and added a check so that this won't happen again.

It's available on NPM now!
