### ISSUE TITLE
attrs and as support?

### ISSUE THREAD

**Issue by janosh** [jacobwgillespie/styled-icons#465]
Hey Jacob, does `styled-icons` support `styled-components`'s [`attrs` constructor](https://www.styled-components.com/docs/api#attrs) and [`as` polymorphic prop](https://www.styled-components.com/docs/api#as-polymorphic-prop)?

I have a `Toggle` component on which I tried to use both but neither seemed to have any effect.
```jsx
import React from 'react'
import styled from 'styled-components'

import { Close } from 'styled-icons/material/Close'
import { Menu } from 'styled-icons/feather/Menu'

const Toggle = styled(Close).attrs({ size: `1em` })`
  cursor: pointer;
  ${props => (props.inside ? inNavToggle : inHeaderToggle)};
  ${navLinkStyle};
`

const Nav = props => (
     ...
     <Toggle onClick={this.toggleNav} as={Menu} />
     ...
)
```

**Comment by jacobwgillespie** [comment]
Hey @janosh, it should support those yes - let me take a look into this, it appears I may need to make some modifications to support those.  Right now, it looks like Styled Components is interpreting `as={Menu}` as `as="svg"` which leaves the icon tag unchanged and doesn't change its children.  I believe I know how to resolve this.

**Comment by jacobwgillespie** [comment]
Thanks for your patience @janosh, this should be fixed in v5.7.0!  🎉

**Comment by janosh** [comment]
@jacobwgillespie Thanks a lot for the fix! I can confirm both `attr` and `as` are working under v5.7.0.

**Comment by janosh** [comment]
One issue that I believe arose due to this fix is that I now get about a dozen React warnings in the browser console along the lines of
> Warning: React does not recognize the `showBelow` prop on a DOM element.

Is there a way for `styled-icons` to intercept invalid DOM attributes and prevent them from reaching DOM nodes?

**Comment by janosh** [comment]
Excellent! Thanks for the quick response. Fix confirmed.
