### ISSUE TITLE
Support on OpenCollective

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#484]
Hi there!

We've been using styled-icons for https://opencollective.com for some weeks now, and I've started using it on some of my personal projects. I'm really happy with this library and would like to say thanks, so I've pledged to give $5/month on https://opencollective.com/styled-icons

I'm sure other people would be happy to support the work that you're doing here :slightly_smiling_face:

**Comment by jacobwgillespie** [comment]
Nice, thanks for the support!  I'll get OpenCollective set up here...  Right now, the flow for claiming the collective doesn't seem to be functioning:

<img width="553" alt="screenshot 2018-12-20 17 29 26" src="https://user-images.githubusercontent.com/130874/50316595-e4a53980-047c-11e9-90f5-bc43f97eefea.png">

**Comment by Betree** [comment]
Well this is not good, sorry about that :disappointed: I've opened an issue and will keep you updated very soon.

**Comment by jacobwgillespie** [comment]
Awesome, thanks for the quick turnaround, I was able to claim the collective!  🎉

**Comment by Betree** [comment]
I've made a first donation from my personal account, will start monthly support using Open Collective gift card in January :wink: Thanks again for the great work, hope you'll get the support this deserves!

**Comment by jacobwgillespie** [comment]
Awesome, thank you so much!  I appreciate it and am glad you're finding the project useful.  👍
