### ISSUE TITLE
Integrate IcoMoon icons

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#491]
I don't especially need it, but I've used [IcoMoon](https://icomoon.io/#icons-icomoon) in the past. They have a large set of good-quality icons, with a good part licensed under GPL / CC BY 4.0 and provide a variety of formats (including SVGs). 

See their free 490 icons here: https://icomoon.io/#preview-free

If it's easy to integrate, I think it would be a nice-to-have :slightly_smiling_face:

**Comment by jacobwgillespie** [comment]
Good idea, these have been added in v5.8.0! 🎉 

There's currently an issue displaying them on the icon explorer website, but the build that's building now should deploy and resolve in the next few minutes.

**Comment by jacobwgillespie** [comment]
Deploy successful!  https://styled-icons.js.org/?s=icomoon

**Comment by Betree** [comment]
Wow that was fast @jacobwgillespie :smiley: Happy holidays to you!

**Comment by Betree** [comment]
I found a bunch of other libraries that were listed on icomoon. Do you have a rule about what should be added or not (except the license)? Should I open issues to list them?

**Comment by jacobwgillespie** [comment]
Awesome - happy holidays to you as well!

Cool, yeah no rule besides license - at some point I really need to revamp the website so that you can filter by icon pack, etc, but yeah if you have other packs you'd like to see, feel free to send them over!
