### ISSUE TITLE
Icon pack proposal: Entypo+

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#496]
- Name: `Entypo+`
- License: `CC BY-SA 4.0`
- NPM package: [entypo](https://github.com/hypermodules/entypo)
- Website (if any): http://www.entypo.com/

![Preview](https://github.com/hypermodules/entypo/raw/master/screenshot.png)

**Comment by jacobwgillespie** [comment]
This has been published as v9.5.0! 🎉
