### ISSUE TITLE
Icon pack proposal: Zondicons

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#497]
- Name: Zondicons
- License: `CC-BY-4.0`
- NPM package: [zondicons](https://www.npmjs.com/package/zondicons)
- Website (if any): https://www.zondicons.com

![Preview](https://user-images.githubusercontent.com/1556356/50417008-e3c92a80-0823-11e9-9b14-3dcd2e751085.png)

**Comment by jacobwgillespie** [comment]
This has been published as v9.5.0! 🎉
