### ISSUE TITLE
Icon pack proposal: Open Iconic

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#499]
- Name: `Open Iconic`
- License: `MIT License`
- NPM package: [open-iconic](https://www.npmjs.com/package/open-iconic)
- Website (if any): https://useiconic.com/open/

![Preview](https://user-images.githubusercontent.com/1556356/50417147-e2e4c880-0824-11e9-89ac-55b30d40303a.png)

**Comment by jacobwgillespie** [comment]
This has been published as v9.5.0! 🎉
