### ISSUE TITLE
Icon pack proposal: Foundation Icons

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#501]
- Name: `Foundation Icons`
- License: `MIT`
- NPM package: [@icon/foundation-icons](https://www.npmjs.com/package/@icon/foundation-icons)
- Website (if any): https://zurb.com/playground/foundation-icon-fonts-3

![image](https://user-images.githubusercontent.com/1556356/50417726-33115a00-0828-11e9-8485-c5be2de0cf1f.png)

**Comment by jacobwgillespie** [comment]
This has been published as v9.5.0! 🎉
