### ISSUE TITLE
Icon pack proposal: Cryptocurrency Icons

### ISSUE THREAD

**Issue by alexmironof** [jacobwgillespie/styled-icons#505]
- Name: `Cryptocurrency Icons`
- License: `CC0-1.0`
- NPM package: `https://www.npmjs.com/package/cryptocurrency-icons`
- Website (if any): `http://cryptoicons.co/`

**Comment by jacobwgillespie** [comment]
Thanks for the proposal, this has been released in v6.2.0! 🎉

**Comment by alexmironof** [comment]
Awesome thanks!
