### ISSUE TITLE
If I want to use an icon on a ::before{content} property, is this possible with this library?

### ISSUE THREAD

**Issue by hanoii** [jacobwgillespie/styled-icons#528]

**Comment by jacobwgillespie** [comment]
I think this is not directly possible - this library provides icons as React / Styled Components, and as far as I'm aware, it's not possible to use a React component in a `::before{content}` CSS property.  

I'll let you know if this is possible in the future, in the meantime I'll close this issue.

**Comment by aakhan89** [comment]
> I think this is not directly possible - this library provides icons as React / Styled Components, and as far as I'm aware, it's not possible to use a React component in a `::before{content}` CSS property.
> 
> I'll let you know if this is possible in the future, in the meantime I'll close this issue.

Any luck ?

**Comment by jacobwgillespie** [comment]
@aakhan89 it doesn't look like React supports this, no - `::before{content}` can only be a string.  You're likely better off wrapping the element in another element like a `<div>` and using CSS positioning to place the icon:

```javascript
<div>
  <Icon />
  <OtherElement />
</div>
```
