### ISSUE TITLE
How to set size, color, etc.. to all styled icon

### ISSUE THREAD

**Issue by aakhan89** [jacobwgillespie/styled-icons#625]
I have a file styledIcon.js and I am using below icons in different components, So I want to set set globally all icon size is "14px" and other things like color etc..

so how can it possible 

`import { ExternalLinkSquareAlt } from 'styled-icons/fa-solid/ExternalLinkSquareAlt'; 
import { Phone } from 'styled-icons/icomoon/Phone'; 
import { Email } from 'styled-icons/material/Email';  

export { ExternalLinkSquareAlt, Phone, Email }`

**Comment by StorytellerCZ** [comment]
I would just create a file where I would apply the styling and export the new variables.

**Comment by aakhan89** [comment]
> I would just create a file where I would apply the styling and export the new variables.

Can you please share example

**Comment by aakhan89** [comment]
> One way I've seen this done is to create a wrapper function that applies your custom styles:
> 
> ```ts
> import styled from 'styled-components'
> 
> function withIconStyles(icon) {
>   return styled(icon)`
>     /* your custom styles here */
>   `
> }
> ```
> 
> Then you can use icons and wrap them in your custom styles:
> 
> ```ts
> import {Email} from 'styled-icons/material/Email'
> 
> const StyledEmail = withIconStyles(Email)
> ```
> 
> In one of the projects I work on, we created a `supportedIcons` file that re-exports all the icons we use in our project:
> 
> ```ts
> export {Bell} from 'styled-icons/fa-solid/Bell'
> export {CheckCircle} from 'styled-icons/fa-solid/CheckCircle'
> export {Plus} from 'styled-icons/fa-solid/Plus'
> ```
> 
> Then we have an `icons` file that re-exports those icons plus the custom styles:
> 
> ```ts
> import styled from 'styled-components'
> import * as supportedIcons from './supportedIcons'
> 
> export const icons = Object.keys(supportedIcons).reduce((styledIcons, name) => {
>   styledIcons[name] = styled(supportedIcons[name])`
>     /* custom styles here */
>     color: red;
>   `
>   return styledIcons
> }, {})
> ```
> 
> Then we can `import {icons} from './icons'` and that object has all the icons imported from `supportedIcons` but with the custom styles applied.
> 
> All that said, if anybody has any other ideas I'd be open to exploring making this a more native feature.

Hi,

Thank you for you reply, i tried the above but not working

**Comment by jacobwgillespie** [comment]
Can you share the code that's broken?  What about it isn't working?

**Comment by jacobwgillespie** [comment]
I'm going to close this, but if it's still not working for you, feel free to post back with a [CodeSandbox](https://codesandbox.io/) example and I'd be happy to see what's broken.

**Comment by cloud-walker** [comment]
> One way I've seen this done is to create a wrapper function that applies your custom styles:
> 
> ```ts
> import styled from 'styled-components'
> 
> function withIconStyles(icon) {
>   return styled(icon)`
>     /* your custom styles here */
>   `
> }
> ```
> 
> Then you can use icons and wrap them in your custom styles:
> 
> ```ts
> import {Email} from 'styled-icons/material/Email'
> 
> const StyledEmail = withIconStyles(Email)
> ```
> 
> In one of the projects I work on, we created a `supportedIcons` file that re-exports all the icons we use in our project:
> 
> ```ts
> export {Bell} from 'styled-icons/fa-solid/Bell'
> export {CheckCircle} from 'styled-icons/fa-solid/CheckCircle'
> export {Plus} from 'styled-icons/fa-solid/Plus'
> ```
> 
> Then we have an `icons` file that re-exports those icons plus the custom styles:
> 
> ```ts
> import styled from 'styled-components'
> import * as supportedIcons from './supportedIcons'
> 
> export const icons = Object.keys(supportedIcons).reduce((styledIcons, name) => {
>   styledIcons[name] = styled(supportedIcons[name])`
>     /* custom styles here */
>     color: red;
>   `
>   return styledIcons
> }, {})
> ```
> 
> Then we can `import {icons} from './icons'` and that object has all the icons imported from `supportedIcons` but with the custom styles applied.
> 
> All that said, if anybody has any other ideas I'd be open to exploring making this a more native feature.

This technique is not optimal for code-splitting, it force to import all supportedIcons at once in every page.

I'm wondering if there is another way, like a static className that identifies all icons, or a data-* attribute, that you can use to hook them.

Another way (maybe more clunky but more styled-components style) could be to have an `Icon` styled component and use it in combination with the styled icons, like that: `<Icon as={KeyboardArrowRight} />` 🤔
