### ISSUE TITLE
Update material ui source to a more recent source

### ISSUE THREAD

**Issue by berndschimmer** [jacobwgillespie/styled-icons#730]
Hi,

the materail ui source on github (https://github.com/google/material-design-icons) is 3 years old and doesn't seem to be maintained any more.
Please update to a more recent source like:
https://github.com/cyberalien/google-material-design-icons-updated

Thx!

**Comment by ismaelheinen** [comment]
Yeah this is important to allow use of different type of material icons, like, outlined, rounded and sharp.

https://material.io/tools/icons/?style=baseline

Super expected feature.

Thanks

**Comment by stramel** [comment]
Would love to see this update. Was looking for `DragIndicator` and couldn't find it.

**Comment by jacobwgillespie** [comment]
Does anyone have a link to such a source?  I would be happy to update, however https://github.com/cyberalien/google-material-design-icons-updated isn't published to NPM and is missing a `version` in its `package.json`, and `@mdi/svg` has a ton of user-submitted icons but isn't up to date with the official Material icons.

**Comment by stramel** [comment]
@jacobwgillespie I will take a look and ping some friends at Google.

**Comment by jacobwgillespie** [comment]
Awesome, thanks!

**Comment by stramel** [comment]
@jacobwgillespie It appears that they are only maintaining the font-icons currently. https://fonts.googleapis.com/icon?family=Material+Icons

You might be able to take that font file and convert it into the SVGs?

Alternatively, the `@material-ui/icons`(https://github.com/mui-org/material-ui/tree/master/packages/material-ui-icons) package has all the up-to-date svgs... so you may want to take a look at how they are accomplishing it and do something similar?

**Comment by stramel** [comment]
@jacobwgillespie I went ahead and made a repo for pulling the latest icons. I plan on publishing it if you think it is a good structure. I also plan on automating the releases whenever a new version of the icons are released. Let me know what you think! 

https://github.com/stramel/material-design-icons-updated

**Comment by stramel** [comment]
@jacobwgillespie I published my library of icons https://www.npmjs.com/package/material-design-icons-updated

Working on automating the releases.

**Comment by jacobwgillespie** [comment]
Thanks for your patience and for @stramel for publishing the updated library and integrating it with `styled-icons` - this should release as v8.4.0 shortly once the CI build completes! 🎉
