### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by linonetwo** [jacobwgillespie/styled-icons#772]
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

```js
import { Close } from 'styled-icons/material';

console.log(Close)
```

In 2.3.1 it logs `ƒ a(){return b(this,a),C(this,e.apply(this,arguments))}`

But in 7.10.0 it logs `{$$typeof: Symbol(react.forward_ref), render: ƒ, displayName: "Close"}` and React throws error.

**Comment by jacobwgillespie** [comment]
Hey, I can take a look at this - would you be able to share the React version you are using?  If you’re able to create a CodeSandbox or repo with the issue too that would be awesome

**Comment by linonetwo** [comment]
Oh, I'm in:

```js
"react": "^16.8.6",
"styled-components": "^3.3.3",
```

Repo is difficult to share, because it's a terminal's plugin https://github.com/linonetwo/hyper-visual/blob/master/src/components/MainPanel.js#L9

Maybe it's caused by outdated styled-components?

https://stackblitz.com/edit/react-rpwzcw

**Comment by jacobwgillespie** [comment]
Ah, nice, I use Hyper as well, `hyper-visual` is cool 👍 

Yep!  I believe that's the issue, the breaking change for v4.0.0 of `styled-icons` was requiring at least v4.1.0 of `styled-components`.

I took a look a the [CHANGELOG](https://github.com/jacobwgillespie/styled-icons/blob/master/CHANGELOG.md) and your code, and that's the only breaking change I think would affect `hyper-visual`, so most likely if you upgrade Styled Components it should all work.

There's a nice upgrade FAQ here: https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4

**Comment by linonetwo** [comment]
Thank you, I found that styled-components depends on latest react-dom for `forwardRef`, but when I upgrade react-dom, it throws ( so I downgrade it and then found what I stated in this issue )

I'm closing this untill hyper upgrade it's react-dom.
https://github.com/zeit/hyper/issues/3573

**Comment by jacobwgillespie** [comment]
Cool, glad we found the issue source, hopefully `hyper` upgrades shortly 👍
