### ISSUE TITLE
Error for all icons when using with TypeScript

### ISSUE THREAD

**Issue by Alwox** [jacobwgillespie/styled-icons#817]
When I want to use some icon im my project with TypeScript I'm getting errors like this: 
```
ERROR in [at-loader] ./node_modules/styled-icons/fa-solid/YinYang/YinYang.d.ts:3:85 
    TS2344: Type '"string" | "style" | "title" | "clipPath" | "filter" | "mask" | "className" | "color" | "height" | "id" | "lang" | "max" | "media" | "method" | "min" | "name" | "target" | "type" | ... 450 more ... | "size"' does not satisfy the constraint '"string" | "style" | "title" | "clipPath" | "filter" | "mask" | "ref" | "className" | "color" | "height" | "id" | "lang" | "max" | "media" | "method" | "min" | "name" | "target" | ... 403 more ... | "size"'.
  Type '"aria-activedescendant"' is not assignable to type '"string" | "style" | "title" | "clipPath" | "filter" | "mask" | "ref" | "className" | "color" | "height" | "id" | "lang" | "max" | "media" | "method" | "min" | "name" | "target" | ... 403 more ... | "size"'.
```
for all icons (more than 1800 errors). And Im importing only one icon.

Also I would like to import them like this `import { Home } from 'styled-icons/fa-solid';` but it also cause error
```Error:(29, 12) TS2740: Type '{ size: string; title: string; }' is missing the following properties from type 'Pick<StyledIconProps, "string"...```
I found this workaround: `const Home: any = require('styled-icons/fa-solid/Home');`. Any suggestion what I'm doing wrong? (using last `7.15.1` version of styled-icons)

**Comment by jacobwgillespie** [comment]
Hey, can you share which version of `styled-components` and `@types/styled-components` and `@types/react`?  I've seen this error before when either of the types packages are out of date (and thus are missing the ARIA attributes).

**Comment by Alwox** [comment]
`"styled-components": "4.2.0"`
`"@types/styled-components": "4.1.8"`
`"@types/react": "16.8.13"`

**Comment by jacobwgillespie** [comment]
Cool, it looks like the issue is with `@types/react` - you are using v16.8.13.  In v16.8.14, the ARIA attributes were added to SVGs.  Can you try upgrading to that version, or to the latest 16.8.17?  That should resolve.

**Comment by Alwox** [comment]
Thank you! Works like a charm 🎉  Maybe info about it could be added to readme?

**Comment by jacobwgillespie** [comment]
Nice, glad we found the cause - I added a note to the README.  Thanks again!
