### ISSUE TITLE
Unhandled Rejection (Error): Cannot create styled-component for component: [object Object]

### ISSUE THREAD

**Issue by CristianWesleyFront** [jacobwgillespie/styled-icons#828]
Instalei esse pacote via npm, porem por algum motivo que não consegue identificar essa mensagem de erro aparece, já tentei reinstalar varias vezes , tanto o styledComponents , styledIcons, @types/react , utilizar numa tela apenas o código de teste :
import styled from 'styled-components'
import {Zap} from 'styled-icons/octicons/Zap'

const RedZap = styled(Zap)`
  color: red;
`

const App = () => <RedZap />

porem não funciona, alguém poderia me ajudar :D

**Comment by jacobwgillespie** [comment]
Can you let me know which version of `react` and `styled-components` you are using?  If you are able to create an example of the problem as a https://codesandbox.io or GitHub repository, that would be helpful - I would be happy to help!

**Comment by CristianWesleyFront** [comment]
sorry, but now I realized that my dependence on the styled component was not in the last version of the project, thank you

**Comment by jacobwgillespie** [comment]
Great, glad you were able to get it to work! 👍
