### ISSUE TITLE
Rankings icons

### ISSUE THREAD

**Issue by zenVentzi** [jacobwgillespie/styled-icons#850]
Excuse me for not using the template, but it probably doesn't fit my proposal. A simple google search of ["rankings icon"](https://www.google.com/search?q=rankings+icon&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiPva2nvdfiAhWp5KYKHaKKAe4Q_AUIECgB&biw=2048&bih=963) gives examples of what I am referring to.

**Comment by jacobwgillespie** [comment]
Thanks for opening the issue!  Do you know of any open-source icon packs that include a rankings icon?  I did a quick check on those Google results and didn't fine one, most of them are paid individual icons.

But if there is an icon pack that's open-source and includes such an icon, I would be happy to get it integrated!

**Comment by zenVentzi** [comment]
Appreciate the feedback! I understand. I will let you know if I stumble upon any :)
