### ISSUE TITLE
Include "xmlns" attribute by default

### ISSUE THREAD

**Issue by r-inaldi** [jacobwgillespie/styled-icons#887]
Any chance to include `xmlns="http://www.w3.org/2000/svg"` by default?

`background-image: url()` only accepts svg strings with this attribute.

I know I can pass as a prop but in the end it's annoying and it's not a big problem to have it as default prop.

Great lib btw.

**Comment by jacobwgillespie** [comment]
Hey, thanks for the suggestion, just added this, and it will be released in a few minutes after the build completes as v8.3.0!  🎉

**Comment by r-inaldi** [comment]
Nice! Thanks for the addition 🚀
