### ISSUE TITLE
Two Tone options for Material Icons

### ISSUE THREAD

**Issue by fjcero** [jacobwgillespie/styled-icons#932]
Is there a plan to support custom options for Icons, like `twoTones` colors (primary + secondary)?

**Comment by stramel** [comment]
related to #730

**Comment by stramel** [comment]
@fjcero The material two-tone icons use an `opacity: 0.3` for the secondary color. So it will still be styled.

```
styled(AccountCirlce)`
	fill: red;
`
```

**Comment by stramel** [comment]
Related to #506

**Comment by stramel** [comment]
@jacobwgillespie My material icons package has all the Material Icon variants (filled, outlined, twoTone, etc). Did you want to support Icon subsets, and if so, did you have any opinion on how to structure that?

**Comment by jacobwgillespie** [comment]
Right now we have that sort of thing modelled as separate pack names, so like `fa-regular` vs `fa-solid`.  We could potentially have `material-outlined`, `material-twotoned`, etc.

There may be some other ways to do it (`<IconName variant="outline" />`, etc.), but just adding them under new pack names:

1. Already exists
2. We don't have to think about tree shaking / bundle size
3. Doesn't require the upstream icon sources to always bundle every variant of every icon (some of the upstream sources aren't always stable)
4. Would be quick to add

Definitely open to ideas though!

**Comment by stramel** [comment]
Thanks for the quick reply @jacobwgillespie! I didn't realize that we were shipping 2 variants of FontAwesome. I could definitely use the existing setup for releasing the other variants in the short term while we discuss potential other solutions.

I was thinking maybe `material/outlined` and `material/twotoned`. We could have `material` alias to `material/filled`? Converting Font Awesome to this style would be a breaking change, unless we did aliasing until you want to cut a new major release?
