### ISSUE TITLE
Feather Icons are not showing as of 8.4.0

### ISSUE THREAD

**Issue by lennartbuit** [jacobwgillespie/styled-icons#944]
We noticed that 'feather' icons are no longer working since upgrading from 8.3.0 to 8.4.0, the same is happening on the documentation site [here](https://styled-icons.js.org/?s=feather).

All other icon sets appear to be fine.

**Comment by jacobwgillespie** [comment]
Yep, that is a regression, thanks for catching!  I'll push a fix now 👍

**Comment by jacobwgillespie** [comment]
This has been released as v8.4.1 - thanks again!

**Comment by lennartbuit** [comment]
Thanks for the swift response, cheers!
