### ISSUE TITLE
Style a generic styled-icon with Typescript

### ISSUE THREAD

**Issue by dguayrobotiq** [jacobwgillespie/styled-icons#950]
I want to be able to style a styled-icon passed by props to a component. Since `StyledIcon` is only a type, I can't use it in `styled` function. Problem demonstrated: 

```
import React from "react";
import styled from "styled-components";
import { StyledIcon } from "styled-icons/types";

interface IconButtonProps {
  icon:StyledIcon;
  onClick:(event:React.MouseEvent<HTMLElement>) => void;
}

const Icon = styled(StyledIcon)`
    color: blue;
`

const IconButton:React.FC<IconButtonProps> = ({ icon, onClick }) => {
  return (
    <button onClick={onClick}>
      <Icon icon={icon}/>
    </button>
  );
};
```

And then `IconButton` would be used like this:

```
import { CheckboxUnchecked } from "styled-icons/icomoon/CheckboxUnchecked";

<IconButton icon={CheckboxUnchecked} onClick={() => console.log("clicked")}/>
```

With Fontawesome, we can styled the icon without knowing it's type like `const Icon = styled(FontAwesomeIcon) ...`

Also tried taking the type for the icon I set in the type file but it doesn't work: `React.ForwardRefExoticComponent<Pick<StyledIconProps, ...> & React.RefAttributes<SVGSVGElement>>;`

**Comment by stramel** [comment]
@dguayrobotiq Some minor changes would allow you do achieve what you are looking for.

```jsx
import React from "react";
import styled from "styled-components";
import { StyledIcon } from "styled-icons/types";

interface IconButtonProps {
  icon: StyledIcon;
  onClick: (event:React.MouseEvent<HTMLElement>) => void;
}

const IconButton: React.FC<IconButtonProps> = ({ icon: Icon, onClick }) => {
  return (
    <button onClick={onClick}>
      <Icon style={{ color: 'blue' }} />
    </button>
  );
};
```

Usage would still be what you wanted:

```jsx
import { CheckboxUnchecked } from "styled-icons/icomoon/CheckboxUnchecked";

<IconButton icon={CheckboxUnchecked} onClick={() => console.log("clicked")}/>
```

**Comment by dguayrobotiq** [comment]
> @dguayrobotiq Some minor changes would allow you do achieve what you are looking for.
> 
> ```js-jsx
> import React from "react";
> import { StyledIcon } from "styled-icons/types";
> 
> interface IconButtonProps {
>   icon: StyledIcon;
>   onClick: (event:React.MouseEvent<HTMLElement>) => void;
> }
> 
> const IconButton: React.FC<IconButtonProps> = ({ icon: Icon, onClick }) => {
>   return (
>     <button onClick={onClick}>
>       <Icon style={{ color: 'blue' }} />
>     </button>
>   );
> };
> ```
> 
> Usage would still be what you wanted:
> 
> ```js-jsx
> import { CheckboxUnchecked } from "styled-icons/icomoon/CheckboxUnchecked";
> 
> <IconButton icon={CheckboxUnchecked} onClick={() => console.log("clicked")}/>
> ```

This should work but I'd like to style `Icon` as a styled-component

**Comment by stramel** [comment]
@dguayrobotiq If you want to use `styled-components` you would need to style the button instead.

```jsx
const Button = styled.button`
  color: blue;
`

const IconButton: React.FC<IconButtonProps> = ({ icon: Icon, onClick }) => {
  return (
    <Button onClick={onClick}>
      <Icon />
    </Button>
  );
};
```

**Comment by dguayrobotiq** [comment]
@stramel This is working thanks !
