### ISSUE TITLE
Icon pack proposal: Remix Icon

### ISSUE THREAD

**Issue by Betree** [jacobwgillespie/styled-icons#971]
- Name: `Remix Icon`
- License: `Apache License 2.0`
- NPM package: [`remixicon`](https://www.npmjs.com/package/remixicon)
- Website (if any):  https://remixicon.com

> Remix Icon is a set of open-source neutral-style system symbols for designers and developers. Unlike a patchwork icon library, 1700+ icons are all elaborately crafted so that they are born with the gene of readability, consistency and perfect pixels. Each icon was designed in "Outlined" and "Filled" styles based on a 24x24 grid. Of course, all the icons are free for both personal and commercial use.

![image](https://user-images.githubusercontent.com/1556356/65505817-69b8f580-deca-11e9-9b77-af9cb1f4a6bf.png)

**Comment by stramel** [comment]
I can throw a PR out for this really quick.

**Comment by stramel** [comment]
@jacobwgillespie Any thoughts on how to handle these two icons? `bookmark-line` and `book-mark-line`? The OS doesn't like the same name with differences in casing.
